config/routes.rb
Rails.application.routes.draw do
  resources :swipes
  resources :investors
  resources :founders

end

app/models/founder.rb
# == Schema Information
#
# Table name: founders
#
#  id               :integer          not null, primary key
#  founder_id       :integer
#  name             :text
#  company_name     :text
#  email_address    :text
#  password_digest  :text
#  location         :text
#  website          :text
#  profile_picture  :text
#  description      :text
#  industry         :text
#  capital_required :text
#  equity_share     :text
#  video            :text
#  image_one        :text
#  image_two        :text
#  image_three      :text
#  image_four       :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Founder < ActiveRecord::Base
end

app/models/investor.rb
# == Schema Information
#
# Table name: investors
#
#  id              :integer          not null, primary key
#  investor_id     :integer
#  name            :text
#  company_name    :text
#  title           :text
#  email_address   :text
#  password_digest :text
#  website         :text
#  profile_picture :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Investor < ActiveRecord::Base
end

app/models/swipe.rb
# == Schema Information
#
# Table name: swipes
#
#  id          :integer          not null, primary key
#  founder_id  :integer
#  investor_id :integer
#  favourite   :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Swipe < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/founders_controller.rb
class FoundersController < ApplicationController
  before_action :set_founder, only: [:show, :edit, :update, :destroy]

  # GET /founders
  # GET /founders.json
  def index
    @founders = Founder.all
  end

  # GET /founders/1
  # GET /founders/1.json
  def show
  end

  # GET /founders/new
  def new
    @founder = Founder.new
  end

  # GET /founders/1/edit
  def edit
  end

  # POST /founders
  # POST /founders.json
  def create
    @founder = Founder.new(founder_params)

    respond_to do |format|
      if @founder.save
        format.html { redirect_to @founder, notice: 'Founder was successfully created.' }
        format.json { render :show, status: :created, location: @founder }
      else
        format.html { render :new }
        format.json { render json: @founder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /founders/1
  # PATCH/PUT /founders/1.json
  def update
    respond_to do |format|
      if @founder.update(founder_params)
        format.html { redirect_to @founder, notice: 'Founder was successfully updated.' }
        format.json { render :show, status: :ok, location: @founder }
      else
        format.html { render :edit }
        format.json { render json: @founder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /founders/1
  # DELETE /founders/1.json
  def destroy
    @founder.destroy
    respond_to do |format|
      format.html { redirect_to founders_url, notice: 'Founder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_founder
      @founder = Founder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def founder_params
      params.require(:founder).permit(:founder_id, :name, :company_name, :email_address, :password_digest, :location, :website, :profile_picture, :description, :industry, :capital_required, :equity_share, :video, :image_one, :image_two, :image_three, :image_four)
    end
end

app/controllers/investors_controller.rb
class InvestorsController < ApplicationController
  before_action :set_investor, only: [:show, :edit, :update, :destroy]

  # GET /investors
  # GET /investors.json
  def index
    @investors = Investor.all
  end

  # GET /investors/1
  # GET /investors/1.json
  def show
  end

  # GET /investors/new
  def new
    @investor = Investor.new
  end

  # GET /investors/1/edit
  def edit
  end

  # POST /investors
  # POST /investors.json
  def create
    @investor = Investor.new(investor_params)

    respond_to do |format|
      if @investor.save
        format.html { redirect_to @investor, notice: 'Investor was successfully created.' }
        format.json { render :show, status: :created, location: @investor }
      else
        format.html { render :new }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investors/1
  # PATCH/PUT /investors/1.json
  def update
    respond_to do |format|
      if @investor.update(investor_params)
        format.html { redirect_to @investor, notice: 'Investor was successfully updated.' }
        format.json { render :show, status: :ok, location: @investor }
      else
        format.html { render :edit }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investors/1
  # DELETE /investors/1.json
  def destroy
    @investor.destroy
    respond_to do |format|
      format.html { redirect_to investors_url, notice: 'Investor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investor
      @investor = Investor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investor_params
      params.require(:investor).permit(:investor_id, :name, :company_name, :title, :email_address, :password_digest, :website, :profile_picture)
    end
end

app/controllers/swipes_controller.rb
class SwipesController < ApplicationController
  before_action :set_swipe, only: [:show, :edit, :update, :destroy]

  # GET /swipes
  # GET /swipes.json
  def index
    @swipes = Swipe.all
  end

  # GET /swipes/1
  # GET /swipes/1.json
  def show
  end

  # GET /swipes/new
  def new
    @swipe = Swipe.new
  end

  # GET /swipes/1/edit
  def edit
  end

  # POST /swipes
  # POST /swipes.json
  def create
    @swipe = Swipe.new(swipe_params)

    respond_to do |format|
      if @swipe.save
        format.html { redirect_to @swipe, notice: 'Swipe was successfully created.' }
        format.json { render :show, status: :created, location: @swipe }
      else
        format.html { render :new }
        format.json { render json: @swipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /swipes/1
  # PATCH/PUT /swipes/1.json
  def update
    respond_to do |format|
      if @swipe.update(swipe_params)
        format.html { redirect_to @swipe, notice: 'Swipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @swipe }
      else
        format.html { render :edit }
        format.json { render json: @swipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swipes/1
  # DELETE /swipes/1.json
  def destroy
    @swipe.destroy
    respond_to do |format|
      format.html { redirect_to swipes_url, notice: 'Swipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_swipe
      @swipe = Swipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def swipe_params
      params.require(:swipe).permit(:founder_id, :investor_id, :favourite)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/founders_helper.rb
module FoundersHelper
end

app/helpers/investors_helper.rb
module InvestorsHelper
end

app/helpers/swipes_helper.rb
module SwipesHelper
end

app/views/founders/_form.html.erb
<%= form_for(@founder) do |f| %>
  <% if @founder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@founder.errors.count, "error") %> prohibited this founder from being saved:</h2>

      <ul>
      <% @founder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :founder_id %><br>
    <%= f.number_field :founder_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_area :company_name %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_area :email_address %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_area :password_digest %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_area :website %>
  </div>
  <div class="field">
    <%= f.label :profile_picture %><br>
    <%= f.text_area :profile_picture %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :industry %><br>
    <%= f.text_area :industry %>
  </div>
  <div class="field">
    <%= f.label :capital_required %><br>
    <%= f.text_area :capital_required %>
  </div>
  <div class="field">
    <%= f.label :equity_share %><br>
    <%= f.text_area :equity_share %>
  </div>
  <div class="field">
    <%= f.label :video %><br>
    <%= f.text_area :video %>
  </div>
  <div class="field">
    <%= f.label :image_one %><br>
    <%= f.text_area :image_one %>
  </div>
  <div class="field">
    <%= f.label :image_two %><br>
    <%= f.text_area :image_two %>
  </div>
  <div class="field">
    <%= f.label :image_three %><br>
    <%= f.text_area :image_three %>
  </div>
  <div class="field">
    <%= f.label :image_four %><br>
    <%= f.text_area :image_four %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/founders/edit.html.erb
<h1>Editing Founder</h1>

<%= render 'form' %>

<%= link_to 'Show', @founder %> |
<%= link_to 'Back', founders_path %>

app/views/founders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Founders</h1>

<table>
  <thead>
    <tr>
      <th>Founder</th>
      <th>Name</th>
      <th>Company name</th>
      <th>Email address</th>
      <th>Password digest</th>
      <th>Location</th>
      <th>Website</th>
      <th>Profile picture</th>
      <th>Description</th>
      <th>Industry</th>
      <th>Capital required</th>
      <th>Equity share</th>
      <th>Video</th>
      <th>Image one</th>
      <th>Image two</th>
      <th>Image three</th>
      <th>Image four</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @founders.each do |founder| %>
      <tr>
        <td><%= founder.founder_id %></td>
        <td><%= founder.name %></td>
        <td><%= founder.company_name %></td>
        <td><%= founder.email_address %></td>
        <td><%= founder.password_digest %></td>
        <td><%= founder.location %></td>
        <td><%= founder.website %></td>
        <td><%= founder.profile_picture %></td>
        <td><%= founder.description %></td>
        <td><%= founder.industry %></td>
        <td><%= founder.capital_required %></td>
        <td><%= founder.equity_share %></td>
        <td><%= founder.video %></td>
        <td><%= founder.image_one %></td>
        <td><%= founder.image_two %></td>
        <td><%= founder.image_three %></td>
        <td><%= founder.image_four %></td>
        <td><%= link_to 'Show', founder %></td>
        <td><%= link_to 'Edit', edit_founder_path(founder) %></td>
        <td><%= link_to 'Destroy', founder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Founder', new_founder_path %>

app/views/founders/new.html.erb
<h1>New Founder</h1>

<%= render 'form' %>

<%= link_to 'Back', founders_path %>

app/views/founders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Founder:</strong>
  <%= @founder.founder_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @founder.name %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @founder.company_name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @founder.email_address %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @founder.password_digest %>
</p>

<p>
  <strong>Location:</strong>
  <%= @founder.location %>
</p>

<p>
  <strong>Website:</strong>
  <%= @founder.website %>
</p>

<p>
  <strong>Profile picture:</strong>
  <%= @founder.profile_picture %>
</p>

<p>
  <strong>Description:</strong>
  <%= @founder.description %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @founder.industry %>
</p>

<p>
  <strong>Capital required:</strong>
  <%= @founder.capital_required %>
</p>

<p>
  <strong>Equity share:</strong>
  <%= @founder.equity_share %>
</p>

<p>
  <strong>Video:</strong>
  <%= @founder.video %>
</p>

<p>
  <strong>Image one:</strong>
  <%= @founder.image_one %>
</p>

<p>
  <strong>Image two:</strong>
  <%= @founder.image_two %>
</p>

<p>
  <strong>Image three:</strong>
  <%= @founder.image_three %>
</p>

<p>
  <strong>Image four:</strong>
  <%= @founder.image_four %>
</p>

<%= link_to 'Edit', edit_founder_path(@founder) %> |
<%= link_to 'Back', founders_path %>

app/views/investors/_form.html.erb
<%= form_for(@investor) do |f| %>
  <% if @investor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@investor.errors.count, "error") %> prohibited this investor from being saved:</h2>

      <ul>
      <% @investor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :investor_id %><br>
    <%= f.number_field :investor_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_area :company_name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_area :email_address %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_area :password_digest %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_area :website %>
  </div>
  <div class="field">
    <%= f.label :profile_picture %><br>
    <%= f.text_area :profile_picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/investors/edit.html.erb
<h1>Editing Investor</h1>

<%= render 'form' %>

<%= link_to 'Show', @investor %> |
<%= link_to 'Back', investors_path %>

app/views/investors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Investors</h1>

<table>
  <thead>
    <tr>
      <th>Investor</th>
      <th>Name</th>
      <th>Company name</th>
      <th>Title</th>
      <th>Email address</th>
      <th>Password digest</th>
      <th>Website</th>
      <th>Profile picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investors.each do |investor| %>
      <tr>
        <td><%= investor.investor_id %></td>
        <td><%= investor.name %></td>
        <td><%= investor.company_name %></td>
        <td><%= investor.title %></td>
        <td><%= investor.email_address %></td>
        <td><%= investor.password_digest %></td>
        <td><%= investor.website %></td>
        <td><%= investor.profile_picture %></td>
        <td><%= link_to 'Show', investor %></td>
        <td><%= link_to 'Edit', edit_investor_path(investor) %></td>
        <td><%= link_to 'Destroy', investor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Investor', new_investor_path %>

app/views/investors/new.html.erb
<h1>New Investor</h1>

<%= render 'form' %>

<%= link_to 'Back', investors_path %>

app/views/investors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Investor:</strong>
  <%= @investor.investor_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @investor.name %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @investor.company_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @investor.title %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @investor.email_address %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @investor.password_digest %>
</p>

<p>
  <strong>Website:</strong>
  <%= @investor.website %>
</p>

<p>
  <strong>Profile picture:</strong>
  <%= @investor.profile_picture %>
</p>

<%= link_to 'Edit', edit_investor_path(@investor) %> |
<%= link_to 'Back', investors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flickseed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/swipes/_form.html.erb
<%= form_for(@swipe) do |f| %>
  <% if @swipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@swipe.errors.count, "error") %> prohibited this swipe from being saved:</h2>

      <ul>
      <% @swipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :founder_id %><br>
    <%= f.number_field :founder_id %>
  </div>
  <div class="field">
    <%= f.label :investor_id %><br>
    <%= f.number_field :investor_id %>
  </div>
  <div class="field">
    <%= f.label :favourite %><br>
    <%= f.check_box :favourite %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/swipes/edit.html.erb
<h1>Editing Swipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @swipe %> |
<%= link_to 'Back', swipes_path %>

app/views/swipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Swipes</h1>

<table>
  <thead>
    <tr>
      <th>Founder</th>
      <th>Investor</th>
      <th>Favourite</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @swipes.each do |swipe| %>
      <tr>
        <td><%= swipe.founder_id %></td>
        <td><%= swipe.investor_id %></td>
        <td><%= swipe.favourite %></td>
        <td><%= link_to 'Show', swipe %></td>
        <td><%= link_to 'Edit', edit_swipe_path(swipe) %></td>
        <td><%= link_to 'Destroy', swipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Swipe', new_swipe_path %>

app/views/swipes/new.html.erb
<h1>New Swipe</h1>

<%= render 'form' %>

<%= link_to 'Back', swipes_path %>

app/views/swipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Founder:</strong>
  <%= @swipe.founder_id %>
</p>

<p>
  <strong>Investor:</strong>
  <%= @swipe.investor_id %>
</p>

<p>
  <strong>Favourite:</strong>
  <%= @swipe.favourite %>
</p>

<%= link_to 'Edit', edit_swipe_path(@swipe) %> |
<%= link_to 'Back', swipes_path %>